/* <!-- START LICENSE -->


This Software / Program / Source Code Created By Developer From Company GLOBAL CORPORATION
Social Media:

   - Youtube: https://youtube.com/@Global_Corporation 
   - Github: https://github.com/globalcorporation
   - TELEGRAM: https://t.me/GLOBAL_CORP_ORG_BOT

All code script in here created 100% original without copy / steal from other code if we copy we add description source at from top code

If you wan't edit you must add credit me (don't change)

If this Software / Program / Source Code has you

Jika Program ini milik anda dari hasil beli jasa developer di (Global Corporation / apapun itu dari turunan itu jika ada kesalahan / bug / ingin update segera lapor ke sub)

Misal anda beli Beli source code di Slebew CORPORATION anda lapor dahulu di slebew jangan lapor di GLOBAL CORPORATION!

Jika ada kendala program ini (Pastikan sebelum deal project tidak ada negosiasi harga)
Karena jika ada negosiasi harga kemungkinan

1. Software Ada yang di kurangin
2. Informasi tidak lengkap
3. Bantuan Tidak Bisa remote / full time (Ada jeda)

Sebelum program ini sampai ke pembeli developer kami sudah melakukan testing

jadi sebelum nego kami sudah melakukan berbagai konsekuensi jika nego tidak sesuai ? 
Bukan maksud kami menipu itu karena harga yang sudah di kalkulasi + bantuan tiba tiba di potong akhirnya bantuan / software kadang tidak lengkap


<!-- END LICENSE --> */
// ignore_for_file: non_constant_identifier_names, unused_import
import "package:general_lib/general_lib.dart";
// import "dart:convert";

/// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
class LoadStableDiffusionModelFromFileStableDiffusionLibrary
    extends JsonScheme {
  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  LoadStableDiffusionModelFromFileStableDiffusionLibrary(super.rawData);

  /// return default special type @type
  /// "loadStableDiffusionModelFromFileStableDiffusionLibrary"
  static String get defaultDataSpecialType {
    return "loadStableDiffusionModelFromFileStableDiffusionLibrary";
  }

  /// return default data
  ///
  static Map get defaultData {
    return {
      "@type": "loadStableDiffusionModelFromFileStableDiffusionLibrary",
      "model_file_path": "",
      "lora_path": "",
      "taesd_path": "",
      "use_tiny_autoencoder": false,
      "use_flash_attention": false,
      "model_type": 0,
      "schedule": 0,
      "clip_l_path": "",
      "clip_g_path": "",
      "t5xxl_path": "",
      "vae_path": "",
      "embed_dir_path": "",
      "stacked_id_embed_dir": "",
      "clip_skip": 0,
      "vae_tiling": false,
      "control_net_path": "",
      "@return_type": "ok",
      "@extra": ""
    };
  }

  /// check data
  /// if raw data
  /// - rawData["@type"] == loadStableDiffusionModelFromFileStableDiffusionLibrary
  /// if same return true
  bool json_scheme_utils_checkDataIsSameBySpecialType() {
    return rawData["@type"] == defaultData["@type"];
  }

  /// check value data whatever do yout want
  bool json_scheme_utils_checkDataIsSameBuilder({
    required bool Function(Map rawData, Map defaultData) onResult,
  }) {
    return onResult(rawData["@type"], defaultData["@type"]);
  }

  /// create [LoadStableDiffusionModelFromFileStableDiffusionLibrary]
  /// Empty
  static LoadStableDiffusionModelFromFileStableDiffusionLibrary empty() {
    return LoadStableDiffusionModelFromFileStableDiffusionLibrary({});
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  String? get special_type {
    try {
      if (rawData["@type"] is String == false) {
        return null;
      }
      return rawData["@type"] as String;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set special_type(String? value) {
    rawData["@type"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  String? get model_file_path {
    try {
      if (rawData["model_file_path"] is String == false) {
        return null;
      }
      return rawData["model_file_path"] as String;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set model_file_path(String? value) {
    rawData["model_file_path"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  String? get lora_path {
    try {
      if (rawData["lora_path"] is String == false) {
        return null;
      }
      return rawData["lora_path"] as String;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set lora_path(String? value) {
    rawData["lora_path"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  String? get taesd_path {
    try {
      if (rawData["taesd_path"] is String == false) {
        return null;
      }
      return rawData["taesd_path"] as String;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set taesd_path(String? value) {
    rawData["taesd_path"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  bool? get use_tiny_autoencoder {
    try {
      if (rawData["use_tiny_autoencoder"] is bool == false) {
        return null;
      }
      return rawData["use_tiny_autoencoder"] as bool;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set use_tiny_autoencoder(bool? value) {
    rawData["use_tiny_autoencoder"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  bool? get use_flash_attention {
    try {
      if (rawData["use_flash_attention"] is bool == false) {
        return null;
      }
      return rawData["use_flash_attention"] as bool;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set use_flash_attention(bool? value) {
    rawData["use_flash_attention"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  num? get model_type {
    try {
      if (rawData["model_type"] is num == false) {
        return null;
      }
      return rawData["model_type"] as num;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set model_type(num? value) {
    rawData["model_type"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  num? get schedule {
    try {
      if (rawData["schedule"] is num == false) {
        return null;
      }
      return rawData["schedule"] as num;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set schedule(num? value) {
    rawData["schedule"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  String? get clip_l_path {
    try {
      if (rawData["clip_l_path"] is String == false) {
        return null;
      }
      return rawData["clip_l_path"] as String;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set clip_l_path(String? value) {
    rawData["clip_l_path"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  String? get clip_g_path {
    try {
      if (rawData["clip_g_path"] is String == false) {
        return null;
      }
      return rawData["clip_g_path"] as String;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set clip_g_path(String? value) {
    rawData["clip_g_path"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  String? get t5xxl_path {
    try {
      if (rawData["t5xxl_path"] is String == false) {
        return null;
      }
      return rawData["t5xxl_path"] as String;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set t5xxl_path(String? value) {
    rawData["t5xxl_path"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  String? get vae_path {
    try {
      if (rawData["vae_path"] is String == false) {
        return null;
      }
      return rawData["vae_path"] as String;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set vae_path(String? value) {
    rawData["vae_path"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  String? get embed_dir_path {
    try {
      if (rawData["embed_dir_path"] is String == false) {
        return null;
      }
      return rawData["embed_dir_path"] as String;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set embed_dir_path(String? value) {
    rawData["embed_dir_path"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  String? get stacked_id_embed_dir {
    try {
      if (rawData["stacked_id_embed_dir"] is String == false) {
        return null;
      }
      return rawData["stacked_id_embed_dir"] as String;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set stacked_id_embed_dir(String? value) {
    rawData["stacked_id_embed_dir"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  num? get clip_skip {
    try {
      if (rawData["clip_skip"] is num == false) {
        return null;
      }
      return rawData["clip_skip"] as num;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set clip_skip(num? value) {
    rawData["clip_skip"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  bool? get vae_tiling {
    try {
      if (rawData["vae_tiling"] is bool == false) {
        return null;
      }
      return rawData["vae_tiling"] as bool;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set vae_tiling(bool? value) {
    rawData["vae_tiling"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  String? get control_net_path {
    try {
      if (rawData["control_net_path"] is String == false) {
        return null;
      }
      return rawData["control_net_path"] as String;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set control_net_path(String? value) {
    rawData["control_net_path"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  String? get special_return_type {
    try {
      if (rawData["@return_type"] is String == false) {
        return null;
      }
      return rawData["@return_type"] as String;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set special_return_type(String? value) {
    rawData["@return_type"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  String? get special_extra {
    try {
      if (rawData["@extra"] is String == false) {
        return null;
      }
      return rawData["@extra"] as String;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set special_extra(String? value) {
    rawData["@extra"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  static LoadStableDiffusionModelFromFileStableDiffusionLibrary create({
    bool schemeUtilsIsSetDefaultData = false,
    String special_type =
        "loadStableDiffusionModelFromFileStableDiffusionLibrary",
    String? model_file_path,
    String? lora_path,
    String? taesd_path,
    bool? use_tiny_autoencoder,
    bool? use_flash_attention,
    num? model_type,
    num? schedule,
    String? clip_l_path,
    String? clip_g_path,
    String? t5xxl_path,
    String? vae_path,
    String? embed_dir_path,
    String? stacked_id_embed_dir,
    num? clip_skip,
    bool? vae_tiling,
    String? control_net_path,
    String special_return_type = "ok",
    String special_extra = "",
  }) {
    // LoadStableDiffusionModelFromFileStableDiffusionLibrary loadStableDiffusionModelFromFileStableDiffusionLibrary = LoadStableDiffusionModelFromFileStableDiffusionLibrary({
    final Map
        loadStableDiffusionModelFromFileStableDiffusionLibrary_data_create_json =
        {
      "@type": special_type,
      "model_file_path": model_file_path,
      "lora_path": lora_path,
      "taesd_path": taesd_path,
      "use_tiny_autoencoder": use_tiny_autoencoder,
      "use_flash_attention": use_flash_attention,
      "model_type": model_type,
      "schedule": schedule,
      "clip_l_path": clip_l_path,
      "clip_g_path": clip_g_path,
      "t5xxl_path": t5xxl_path,
      "vae_path": vae_path,
      "embed_dir_path": embed_dir_path,
      "stacked_id_embed_dir": stacked_id_embed_dir,
      "clip_skip": clip_skip,
      "vae_tiling": vae_tiling,
      "control_net_path": control_net_path,
      "@return_type": special_return_type,
      "@extra": special_extra,
    };

    loadStableDiffusionModelFromFileStableDiffusionLibrary_data_create_json
        .removeWhere((key, value) => value == null);

    if (schemeUtilsIsSetDefaultData) {
      defaultData.forEach((key, value) {
        if (loadStableDiffusionModelFromFileStableDiffusionLibrary_data_create_json
                .containsKey(key) ==
            false) {
          loadStableDiffusionModelFromFileStableDiffusionLibrary_data_create_json[
              key] = value;
        }
      });
    }
    return LoadStableDiffusionModelFromFileStableDiffusionLibrary(
        loadStableDiffusionModelFromFileStableDiffusionLibrary_data_create_json);
  }
}
