// ignore_for_file: non_constant_identifier_names, unused_import
import "package:general_lib/general_lib.dart";
// import "dart:convert";

/// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
class TextToImageStableDiffusionModelFromFileStableDiffusionLibrary
    extends JsonScheme {
  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  TextToImageStableDiffusionModelFromFileStableDiffusionLibrary(super.rawData);

  /// return default special type @type
  /// "textToImageStableDiffusionModelFromFileStableDiffusionLibrary"
  static String get defaultDataSpecialType {
    return "textToImageStableDiffusionModelFromFileStableDiffusionLibrary";
  }

  /// return default data
  ///
  static Map get defaultData {
    return {
      "@type": "textToImageStableDiffusionModelFromFileStableDiffusionLibrary",
      "prompt": "",
      "negative_prompt": "",
      "clip_skip": 1,
      "cfg_scale": 7.0,
      "guidance": 1.0,
      "width": 512,
      "height": 512,
      "sample_method": 0,
      "sample_steps": 20,
      "seed": 42,
      "batch_count": 1,
      "input_id_images_path": "",
      "style_strength": 1.0,
      "control_image_data": [0],
      "control_image_width": 0,
      "control_image_height": 0,
      "control_strength": 0.9,
      "@return_type": "ok",
      "@extra": ""
    };
  }

  /// check data
  /// if raw data
  /// - rawData["@type"] == textToImageStableDiffusionModelFromFileStableDiffusionLibrary
  /// if same return true
  bool json_scheme_utils_checkDataIsSameBySpecialType() {
    return rawData["@type"] == defaultData["@type"];
  }

  /// check value data whatever do yout want
  bool json_scheme_utils_checkDataIsSameBuilder({
    required bool Function(Map rawData, Map defaultData) onResult,
  }) {
    return onResult(rawData["@type"], defaultData["@type"]);
  }

  /// create [TextToImageStableDiffusionModelFromFileStableDiffusionLibrary]
  /// Empty
  static TextToImageStableDiffusionModelFromFileStableDiffusionLibrary empty() {
    return TextToImageStableDiffusionModelFromFileStableDiffusionLibrary({});
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  String? get special_type {
    try {
      if (rawData["@type"] is String == false) {
        return null;
      }
      return rawData["@type"] as String;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set special_type(String? value) {
    rawData["@type"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  String? get prompt {
    try {
      if (rawData["prompt"] is String == false) {
        return null;
      }
      return rawData["prompt"] as String;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set prompt(String? value) {
    rawData["prompt"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  String? get negative_prompt {
    try {
      if (rawData["negative_prompt"] is String == false) {
        return null;
      }
      return rawData["negative_prompt"] as String;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set negative_prompt(String? value) {
    rawData["negative_prompt"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  num? get clip_skip {
    try {
      if (rawData["clip_skip"] is num == false) {
        return null;
      }
      return rawData["clip_skip"] as num;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set clip_skip(num? value) {
    rawData["clip_skip"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  double? get cfg_scale {
    try {
      if (rawData["cfg_scale"] is double == false) {
        return null;
      }
      return rawData["cfg_scale"] as double;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set cfg_scale(double? value) {
    rawData["cfg_scale"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  double? get guidance {
    try {
      if (rawData["guidance"] is double == false) {
        return null;
      }
      return rawData["guidance"] as double;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set guidance(double? value) {
    rawData["guidance"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  num? get width {
    try {
      if (rawData["width"] is num == false) {
        return null;
      }
      return rawData["width"] as num;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set width(num? value) {
    rawData["width"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  num? get height {
    try {
      if (rawData["height"] is num == false) {
        return null;
      }
      return rawData["height"] as num;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set height(num? value) {
    rawData["height"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  num? get sample_method {
    try {
      if (rawData["sample_method"] is num == false) {
        return null;
      }
      return rawData["sample_method"] as num;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set sample_method(num? value) {
    rawData["sample_method"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  num? get sample_steps {
    try {
      if (rawData["sample_steps"] is num == false) {
        return null;
      }
      return rawData["sample_steps"] as num;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set sample_steps(num? value) {
    rawData["sample_steps"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  num? get seed {
    try {
      if (rawData["seed"] is num == false) {
        return null;
      }
      return rawData["seed"] as num;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set seed(num? value) {
    rawData["seed"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  num? get batch_count {
    try {
      if (rawData["batch_count"] is num == false) {
        return null;
      }
      return rawData["batch_count"] as num;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set batch_count(num? value) {
    rawData["batch_count"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  String? get input_id_images_path {
    try {
      if (rawData["input_id_images_path"] is String == false) {
        return null;
      }
      return rawData["input_id_images_path"] as String;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set input_id_images_path(String? value) {
    rawData["input_id_images_path"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  double? get style_strength {
    try {
      if (rawData["style_strength"] is double == false) {
        return null;
      }
      return rawData["style_strength"] as double;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set style_strength(double? value) {
    rawData["style_strength"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  ///
  /// default:
  ///
  ///
  List<num> get control_image_data {
    try {
      if (rawData["control_image_data"] is List == false) {
        return [];
      }
      return (rawData["control_image_data"] as List).cast<num>();
    } catch (e) {
      return [];
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set control_image_data(List<num> value) {
    rawData["control_image_data"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  num? get control_image_width {
    try {
      if (rawData["control_image_width"] is num == false) {
        return null;
      }
      return rawData["control_image_width"] as num;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set control_image_width(num? value) {
    rawData["control_image_width"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  num? get control_image_height {
    try {
      if (rawData["control_image_height"] is num == false) {
        return null;
      }
      return rawData["control_image_height"] as num;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set control_image_height(num? value) {
    rawData["control_image_height"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  double? get control_strength {
    try {
      if (rawData["control_strength"] is double == false) {
        return null;
      }
      return rawData["control_strength"] as double;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set control_strength(double? value) {
    rawData["control_strength"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  String? get special_return_type {
    try {
      if (rawData["@return_type"] is String == false) {
        return null;
      }
      return rawData["@return_type"] as String;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set special_return_type(String? value) {
    rawData["@return_type"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  String? get special_extra {
    try {
      if (rawData["@extra"] is String == false) {
        return null;
      }
      return rawData["@extra"] as String;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set special_extra(String? value) {
    rawData["@extra"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  static TextToImageStableDiffusionModelFromFileStableDiffusionLibrary create({
    bool schemeUtilsIsSetDefaultData = false,
    String special_type =
        "textToImageStableDiffusionModelFromFileStableDiffusionLibrary",
    String? prompt,
    String? negative_prompt,
    num? clip_skip,
    double? cfg_scale,
    double? guidance,
    num? width,
    num? height,
    num? sample_method,
    num? sample_steps,
    num? seed,
    num? batch_count,
    String? input_id_images_path,
    double? style_strength,
    List<num>? control_image_data,
    num? control_image_width,
    num? control_image_height,
    double? control_strength,
    String special_return_type = "ok",
    String special_extra = "",
  }) {
    // TextToImageStableDiffusionModelFromFileStableDiffusionLibrary textToImageStableDiffusionModelFromFileStableDiffusionLibrary = TextToImageStableDiffusionModelFromFileStableDiffusionLibrary({
    final Map
        textToImageStableDiffusionModelFromFileStableDiffusionLibrary_data_create_json =
        {
      "@type": special_type,
      "prompt": prompt,
      "negative_prompt": negative_prompt,
      "clip_skip": clip_skip,
      "cfg_scale": cfg_scale,
      "guidance": guidance,
      "width": width,
      "height": height,
      "sample_method": sample_method,
      "sample_steps": sample_steps,
      "seed": seed,
      "batch_count": batch_count,
      "input_id_images_path": input_id_images_path,
      "style_strength": style_strength,
      "control_image_data": control_image_data,
      "control_image_width": control_image_width,
      "control_image_height": control_image_height,
      "control_strength": control_strength,
      "@return_type": special_return_type,
      "@extra": special_extra,
    };

    textToImageStableDiffusionModelFromFileStableDiffusionLibrary_data_create_json
        .removeWhere((key, value) => value == null);

    if (schemeUtilsIsSetDefaultData) {
      defaultData.forEach((key, value) {
        if (textToImageStableDiffusionModelFromFileStableDiffusionLibrary_data_create_json
                .containsKey(key) ==
            false) {
          textToImageStableDiffusionModelFromFileStableDiffusionLibrary_data_create_json[
              key] = value;
        }
      });
    }
    return TextToImageStableDiffusionModelFromFileStableDiffusionLibrary(
        textToImageStableDiffusionModelFromFileStableDiffusionLibrary_data_create_json);
  }
}
