include: package:lints/recommended.yaml
analyzer:
  exclude:
    - test
    - dev
    - templates
  errors:
    todo: ignore
    unnecessary_brace_in_string_interps: ignore
    unnecessary_string_interpolations: ignore
linter:
  rules:
    - public_member_api_docs
    - always_declare_return_types
