/* <!-- START LICENSE -->


This Software / Program / Source Code Created By Developer From Company GLOBAL CORPORATION
Social Media:

   - Youtube: https://youtube.com/@Global_Corporation 
   - Github: https://github.com/globalcorporation
   - TELEGRAM: https://t.me/GLOBAL_CORP_ORG_BOT

All code script in here created 100% original without copy / steal from other code if we copy we add description source at from top code

If you wan't edit you must add credit me (don't change)

If this Software / Program / Source Code has you

Jika Program ini milik anda dari hasil beli jasa developer di (Global Corporation / apapun itu dari turunan itu jika ada kesalahan / bug / ingin update segera lapor ke sub)

Misal anda beli Beli source code di Slebew CORPORATION anda lapor dahulu di slebew jangan lapor di GLOBAL CORPORATION!

Jika ada kendala program ini (Pastikan sebelum deal project tidak ada negosiasi harga)
Karena jika ada negosiasi harga kemungkinan

1. Software Ada yang di kurangin
2. Informasi tidak lengkap
3. Bantuan Tidak Bisa remote / full time (Ada jeda)

Sebelum program ini sampai ke pembeli developer kami sudah melakukan testing

jadi sebelum nego kami sudah melakukan berbagai konsekuensi jika nego tidak sesuai ? 
Bukan maksud kami menipu itu karena harga yang sudah di kalkulasi + bantuan tiba tiba di potong akhirnya bantuan / software kadang tidak lengkap


<!-- END LICENSE --> */
import 'dart:io';
import 'package:general_lib/general_lib.dart';
import "package:path/path.dart" as path;
import 'package:stable_diffusion_library/schemes/stable_diffusion/stable_diffusion.dart';

void main(List<String> args) async {
  final Directory directoryBaseScheme =
      Directory(path.join(Directory.current.path, "lib", "scheme"))
          .generalLibUtilsDangerRecreate();

  final Directory directoryScheme =
      Directory(path.join(directoryBaseScheme.path, "scheme"))
          .generalLibUtilsDangerRecreate();
  final Directory directoryDatabaseUniverseScheme =
      Directory(path.join(directoryBaseScheme.path, "database_universe_scheme"))
          .generalLibUtilsDangerRecreate();

  final String comment =
      "/// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer";

  /// generate schemes
  {
    for (int i = 0; i < stableDiffusionLibraryApiSchemes.length; i++) {
      final Map<String, dynamic> values = {
        "@extra": "",
      };
      if (stableDiffusionLibraryApiSchemes[i]["@return_type"] is String ==
          false) {
        stableDiffusionLibraryApiSchemes[i]["@return_type"] = "ok";
      }
      for (final element in values.entries) {
        stableDiffusionLibraryApiSchemes[i][element.key] = element.value;
      }
    }
    await jsonToScripts(
      stableDiffusionLibraryApiSchemes,
      comment: comment,
      directory: Directory(path.join(directoryScheme.path, "api"))
          .generalLibUtilsDangerRecreate(),
    );
    await jsonToScripts(
      stableDiffusionLibrarySchemes,
      comment: comment,
      directory: Directory(path.join(directoryScheme.path, "core"))
          .generalLibUtilsDangerRecreate(),
    );
    await jsonToScripts(
      stableDiffusionLibraryDatabaseSchemes,
      comment: comment,
      directory: Directory(path.join(directoryScheme.path, "database"))
          .generalLibUtilsDangerRecreate(),
    );
    await jsonToScripts(
      stableDiffusionLibraryRespondSchemes,
      comment: comment,
      directory: Directory(path.join(directoryScheme.path, "respond"))
          .generalLibUtilsDangerRecreate(),
    );
  }
  {
    for (var i = 0; i < stableDiffusionLibraryDatabaseSchemes.length; i++) {
      final Map<String, dynamic> data =
          stableDiffusionLibraryDatabaseSchemes[i];
      if (data["@type"] is String == false) {
        data["@type"] = "";
      }
      final String className = data["@type"];
      if (className.isEmpty) {
        continue;
      }
      final res = jsonToDatabaseUniverse(
        data,
        comment: comment,
        className: className,
      );
      await res.saveToFile(directoryDatabaseUniverseScheme);
    }
  }
  exit(0);
}
