// ignore_for_file: non_constant_identifier_names, unused_import
import "package:general_lib/general_lib.dart";
// import "dart:convert";


/// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer 
class Ok extends JsonScheme {

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  Ok(super.rawData);
  
  /// return default special type @type
  /// "ok"
  static String get defaultDataSpecialType {
    return "ok";
  }

  /// return default data
  /// 
  static Map get defaultData {
    return {"@type":"ok","@extra":""};
  }

  /// check data 
  /// if raw data 
  /// - rawData["@type"] == ok
  /// if same return true
  bool json_scheme_utils_checkDataIsSameBySpecialType() {
    return rawData["@type"] == defaultData["@type"];
  }

  /// check value data whatever do yout want
  bool json_scheme_utils_checkDataIsSameBuilder({
    required bool Function(Map rawData, Map defaultData) onResult,
  }) {
    return onResult(rawData["@type"], defaultData["@type"]);
  }

  

  /// create [Ok]
  /// Empty  
  static Ok empty() {
    return Ok({});
  }

  

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  String? get special_type {
    try {
      if (rawData["@type"] is String == false){
        return null;
      }
      return rawData["@type"] as String;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set special_type(String? value) {
    rawData["@type"] = value;
  }


  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  String? get special_extra {
    try {
      if (rawData["@extra"] is String == false){
        return null;
      }
      return rawData["@extra"] as String;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set special_extra(String? value) {
    rawData["@extra"] = value;
  }


  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  static Ok create({
              bool schemeUtilsIsSetDefaultData = false,

    String special_type = "ok",
    String special_extra = "",
})  {
    // Ok ok = Ok({
final Map ok_data_create_json = {
  
      "@type": special_type,
      "@extra": special_extra,


};


          ok_data_create_json.removeWhere((key, value) => value == null);

    if (schemeUtilsIsSetDefaultData) {
      defaultData.forEach((key, value) {
        if (ok_data_create_json.containsKey(key) == false) {
          ok_data_create_json[key] = value;
        }
      });
    }
return Ok(ok_data_create_json);


      }
}