// ignore_for_file: non_constant_identifier_names, unused_import
import "package:general_lib/general_lib.dart";
// import "dart:convert";

/// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
class UpdateStableDiffusionLogMessageStableDiffusionLibrary extends JsonScheme {
  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  UpdateStableDiffusionLogMessageStableDiffusionLibrary(super.rawData);

  /// return default special type @type
  /// "updateStableDiffusionLogMessageStableDiffusionLibrary"
  static String get defaultDataSpecialType {
    return "updateStableDiffusionLogMessageStableDiffusionLibrary";
  }

  /// return default data
  ///
  static Map get defaultData {
    return {
      "@type": "updateStableDiffusionLogMessageStableDiffusionLibrary",
      "level": 0,
      "message": "",
      "seed": 0,
      "@extra": ""
    };
  }

  /// check data
  /// if raw data
  /// - rawData["@type"] == updateStableDiffusionLogMessageStableDiffusionLibrary
  /// if same return true
  bool json_scheme_utils_checkDataIsSameBySpecialType() {
    return rawData["@type"] == defaultData["@type"];
  }

  /// check value data whatever do yout want
  bool json_scheme_utils_checkDataIsSameBuilder({
    required bool Function(Map rawData, Map defaultData) onResult,
  }) {
    return onResult(rawData["@type"], defaultData["@type"]);
  }

  /// create [UpdateStableDiffusionLogMessageStableDiffusionLibrary]
  /// Empty
  static UpdateStableDiffusionLogMessageStableDiffusionLibrary empty() {
    return UpdateStableDiffusionLogMessageStableDiffusionLibrary({});
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  String? get special_type {
    try {
      if (rawData["@type"] is String == false) {
        return null;
      }
      return rawData["@type"] as String;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set special_type(String? value) {
    rawData["@type"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  num? get level {
    try {
      if (rawData["level"] is num == false) {
        return null;
      }
      return rawData["level"] as num;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set level(num? value) {
    rawData["level"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  String? get message {
    try {
      if (rawData["message"] is String == false) {
        return null;
      }
      return rawData["message"] as String;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set message(String? value) {
    rawData["message"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  num? get seed {
    try {
      if (rawData["seed"] is num == false) {
        return null;
      }
      return rawData["seed"] as num;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set seed(num? value) {
    rawData["seed"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  String? get special_extra {
    try {
      if (rawData["@extra"] is String == false) {
        return null;
      }
      return rawData["@extra"] as String;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set special_extra(String? value) {
    rawData["@extra"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  static UpdateStableDiffusionLogMessageStableDiffusionLibrary create({
    bool schemeUtilsIsSetDefaultData = false,
    String special_type =
        "updateStableDiffusionLogMessageStableDiffusionLibrary",
    num? level,
    String? message,
    num? seed,
    String special_extra = "",
  }) {
    // UpdateStableDiffusionLogMessageStableDiffusionLibrary updateStableDiffusionLogMessageStableDiffusionLibrary = UpdateStableDiffusionLogMessageStableDiffusionLibrary({
    final Map
        updateStableDiffusionLogMessageStableDiffusionLibrary_data_create_json =
        {
      "@type": special_type,
      "level": level,
      "message": message,
      "seed": seed,
      "@extra": special_extra,
    };

    updateStableDiffusionLogMessageStableDiffusionLibrary_data_create_json
        .removeWhere((key, value) => value == null);

    if (schemeUtilsIsSetDefaultData) {
      defaultData.forEach((key, value) {
        if (updateStableDiffusionLogMessageStableDiffusionLibrary_data_create_json
                .containsKey(key) ==
            false) {
          updateStableDiffusionLogMessageStableDiffusionLibrary_data_create_json[
              key] = value;
        }
      });
    }
    return UpdateStableDiffusionLogMessageStableDiffusionLibrary(
        updateStableDiffusionLogMessageStableDiffusionLibrary_data_create_json);
  }
}
