// ignore_for_file: non_constant_identifier_names, unused_import
import "package:general_lib/general_lib.dart";
// import "dart:convert";


/// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer 
class UpdateStableDiffusionGeneratedImageStableDiffusionLibrary extends JsonScheme {

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  UpdateStableDiffusionGeneratedImageStableDiffusionLibrary(super.rawData);
  
  /// return default special type @type
  /// "updateStableDiffusionGeneratedImageStableDiffusionLibrary"
  static String get defaultDataSpecialType {
    return "updateStableDiffusionGeneratedImageStableDiffusionLibrary";
  }

  /// return default data
  /// 
  static Map get defaultData {
    return {"@type":"updateStableDiffusionGeneratedImageStableDiffusionLibrary","is_done":false,"image_rgba_bytes":[0],"width":0,"height":0,"@extra":""};
  }

  /// check data 
  /// if raw data 
  /// - rawData["@type"] == updateStableDiffusionGeneratedImageStableDiffusionLibrary
  /// if same return true
  bool json_scheme_utils_checkDataIsSameBySpecialType() {
    return rawData["@type"] == defaultData["@type"];
  }

  /// check value data whatever do yout want
  bool json_scheme_utils_checkDataIsSameBuilder({
    required bool Function(Map rawData, Map defaultData) onResult,
  }) {
    return onResult(rawData["@type"], defaultData["@type"]);
  }

  

  /// create [UpdateStableDiffusionGeneratedImageStableDiffusionLibrary]
  /// Empty  
  static UpdateStableDiffusionGeneratedImageStableDiffusionLibrary empty() {
    return UpdateStableDiffusionGeneratedImageStableDiffusionLibrary({});
  }

  

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  String? get special_type {
    try {
      if (rawData["@type"] is String == false){
        return null;
      }
      return rawData["@type"] as String;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set special_type(String? value) {
    rawData["@type"] = value;
  }


  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  bool? get is_done {
    try {
      if (rawData["is_done"] is bool == false){
        return null;
      }
      return rawData["is_done"] as bool;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set is_done(bool? value) {
    rawData["is_done"] = value;
  }


  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  ///
  /// default:
  /// 
  /// 
  List<num> get image_rgba_bytes {
    try {
      if (rawData["image_rgba_bytes"] is List == false){
        return [];
      }
      return (rawData["image_rgba_bytes"] as List).cast<num>();
    } catch (e) {
      return [];
    }
  }


  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set image_rgba_bytes(List<num> value) {
    rawData["image_rgba_bytes"] = value;
  }


  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  num? get width {
    try {
      if (rawData["width"] is num == false){
        return null;
      }
      return rawData["width"] as num;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set width(num? value) {
    rawData["width"] = value;
  }


  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  num? get height {
    try {
      if (rawData["height"] is num == false){
        return null;
      }
      return rawData["height"] as num;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set height(num? value) {
    rawData["height"] = value;
  }


  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  String? get special_extra {
    try {
      if (rawData["@extra"] is String == false){
        return null;
      }
      return rawData["@extra"] as String;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set special_extra(String? value) {
    rawData["@extra"] = value;
  }


  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  static UpdateStableDiffusionGeneratedImageStableDiffusionLibrary create({
              bool schemeUtilsIsSetDefaultData = false,

    String special_type = "updateStableDiffusionGeneratedImageStableDiffusionLibrary",
    bool? is_done,
      List<num>? image_rgba_bytes,
    num? width,
    num? height,
    String special_extra = "",
})  {
    // UpdateStableDiffusionGeneratedImageStableDiffusionLibrary updateStableDiffusionGeneratedImageStableDiffusionLibrary = UpdateStableDiffusionGeneratedImageStableDiffusionLibrary({
final Map updateStableDiffusionGeneratedImageStableDiffusionLibrary_data_create_json = {
  
      "@type": special_type,
      "is_done": is_done,
      "image_rgba_bytes": image_rgba_bytes,
      "width": width,
      "height": height,
      "@extra": special_extra,


};


          updateStableDiffusionGeneratedImageStableDiffusionLibrary_data_create_json.removeWhere((key, value) => value == null);

    if (schemeUtilsIsSetDefaultData) {
      defaultData.forEach((key, value) {
        if (updateStableDiffusionGeneratedImageStableDiffusionLibrary_data_create_json.containsKey(key) == false) {
          updateStableDiffusionGeneratedImageStableDiffusionLibrary_data_create_json[key] = value;
        }
      });
    }
return UpdateStableDiffusionGeneratedImageStableDiffusionLibrary(updateStableDiffusionGeneratedImageStableDiffusionLibrary_data_create_json);


      }
}